version: "3.9" 
services:  
  boardgamereportsservice:
    build: ./BoardgameReportsService
    image: deshie/boardgamereportsservice
    restart: always
    ports:
      - 3004:80

  monopolyservice:
    build: ./MonopolyService
    image: deshie/monopolyservice
    restart: always
    ports:
      - 3002:80
    
  eclipseservice:
    build: ./EclipseService
    image: deshie/eclipseservice
    restart: always
    ports:
      - 3001:80

  authservice:
    build: ./AuthenticationService
    image: deshie/authservice
    restart: always
    ports:
      - 3003:80

  
  
